### ISSUE TITLE
Autodetect hamster-cli executable

### ISSUE THREAD

**Issue by johanv** [fmeynadier/taskwarrior-hamster-hook#1]
I am using Fedora 24, and on my system I need to call `hamster` instead of `hamster-cli`. Maybe we can autodetect the executable to use?

**Comment by fmeynadier** [comment]
Thanks for the feedback. Additionaly I should have tested the presence of hamster-cli anyway, and return a proper error message in case it can't be found. 

Can you try the latest master (i.e.  a85a026) ?
